### ISSUE TITLE
Write a description of the Tangram game that you want to implement

### ISSUE THREAD

**Issue by vikraman** [edwardchennn/elm-tangram#1]
List of things to write:

- [x] What is the game?
- [x] List of features
- [x] How does the player interact with the game?
- [x] How is it scored?

List of deliverables:

- [x] What will you build?
- [x] What is the input? What is the output?
- [x] What is the approximate timeline?

**Comment by Edward4Run** [comment]
- What is the game?
- List of features
- How does the player interact with the game?
- How is it scored?

**Comment by vikraman** [comment]
What's happening? I don't see any files in the repository with your writeup.

**Comment by eddysaynun** [comment]
> What's happening? I don't see any files in the repository with your writeup.

Sorry, I haven’t finished it. Just try how to put something on Github.
So I need to upload files instead of commenting here?

**Comment by vikraman** [comment]
This is just an issue to track what you're doing. Please use the repository for your work.

- [x] Learn how to use git: https://guides.github.com/introduction/git-handbook/
- [x] Learn how to use github: https://guides.github.com/activities/hello-world/

**Comment by vikraman** [comment]
I think this is all done.
